version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing Trivy..."
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
  pre_build:
    commands:
      - echo "Cleaning old builds..."
      - mvn clean package -DskipTests
  build:
    commands:
      - echo "Updating Trivy DB..."
      - ./bin/trivy fs --download-db-only
      - echo "Running Trivy scan on build artifacts..."
      # Fail if HIGH or CRITICAL vulnerabilities are found
      - ./bin/trivy fs --exit-code 1 --severity HIGH,CRITICAL target/onlinebookstore.war
  post_build:
    commands:
      - echo "Trivy scan completed."
artifacts:
  files:
    - target/**
    - appspec.yml
    - scripts/*
