version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
        - mvn package
        - mkdir output
        - cp target/*.war output/books.war
artifacts:
  files:
        - 'output/*.war'
        - appspec.yaml
        - scripts/*
