version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "===== Installing Trivy ====="
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
      - ./bin/trivy --version

  pre_build:
    commands:
      - echo "===== Building app before scanning ====="
      - mvn clean package -DskipTests && sleep 20

  build:
    commands:
      - echo "===== Checking for build artifact ====="
      - |
        ls -l target/ && pwd
        if [ ! -f target/onlinebookstore.war ]; then
          echo "ERROR: No WAR file found in target/ — build failed or wrong path.";
          exit 1;
        fi

      - echo "===== Updating Trivy vulnerability database ====="
      - ./bin/trivy fs --download-db-only

      - echo "===== Running Trivy scan on JAR ====="
      - sleep 10 && ./bin/trivy fs --exit-code 1 --severity HIGH,CRITICAL target/**

  post_build:
    commands:
      - echo "===== Trivy scan completed ====="
artifacts:
  files:
    - target/**
    - appspec.yml
    - scripts/*
